[package]
name = "musical_cars_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9.0", features = ["serialize"] }
bevy_asset_loader = "0.14.1"
rand = "0.8.5"
nalgebra = "0.31.4"
entity-gym-rs = { version = "0.8.0", features = ["bevy"] }
serde = "1.0.152"
bincode = "1.3.3"

[dependencies.web-sys]
version = "0.3"
features = ["console"]

[dependencies.bevy_ecs_ldtk]
version = "0.5.0"
features = ["atlas"]

[dependencies.pyo3]
version = "0.15"
features = ["extension-module"]
optional = true

[features]
default = ["serialize_collision"]
graphics = []
serialize_collision = []
load_collision_from_file = []
python = ["pyo3", "entity-gym-rs/python"]